{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE OverloadedStrings #-}

-- | This file is generated by "plutus-preprocessor:plutus-preprocessor"
module Test.Cardano.Ledger.Plutus.Examples where

import Cardano.Ledger.Plutus.Language (
  Language (..),
  Plutus (..),
  PlutusBinary (..),
  PlutusLanguage,
  SLanguage,
 )
import Data.ByteString (ByteString)
import qualified Data.ByteString.Base16 as Base16 (decode)
import qualified Data.ByteString.Short as SBS (toShort)
import GHC.Stack

decodeHexPlutus :: HasCallStack => ByteString -> Plutus l
decodeHexPlutus = either error (Plutus . PlutusBinary . SBS.toShort) . Base16.decode

class PlutusLanguage l => PlutusTestScript (l :: Language) where
  alwaysSucceedsNoDatum :: SLanguage l -> Plutus l
  alwaysSucceedsWithDatum :: SLanguage l -> Plutus l
  alwaysFailsNoDatum :: SLanguage l -> Plutus l
  alwaysFailsWithDatum :: SLanguage l -> Plutus l
  redeemerSameAsDatum :: SLanguage l -> Plutus l
  evenDatum :: SLanguage l -> Plutus l
  evenRedeemerNoDatum :: SLanguage l -> Plutus l
  evenRedeemerWithDatum :: SLanguage l -> Plutus l

instance PlutusTestScript 'PlutusV1 where
  -- Preproceesed PlutusV1 Script:
  -- @@@
  -- alwaysSucceedsNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysSucceedsNoDatum_0 _ _ = GHC.Tuple.Prim.()
  -- @@@
  alwaysSucceedsNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x4701000022120011"
      ]

  -- Preproceesed PlutusV1 Script:
  -- @@@
  -- alwaysSucceedsWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                              PlutusTx.Builtins.Internal.BuiltinData ->
  --                              PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysSucceedsWithDatum_0 _ _ _ = GHC.Tuple.Prim.()
  -- @@@
  alwaysSucceedsWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x480100002221200101"
      ]

  -- Preproceesed PlutusV1 Script:
  -- @@@
  -- alwaysFailsNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                         PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysFailsNoDatum_0 _ _ = PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  alwaysFailsNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x450100002261"
      ]

  -- Preproceesed PlutusV1 Script:
  -- @@@
  -- alwaysFailsWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                           PlutusTx.Builtins.Internal.BuiltinData ->
  --                           PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysFailsWithDatum_0 _ _ _ = PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  alwaysFailsWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x46010000222601"
      ]

  -- Preproceesed PlutusV1 Script:
  -- @@@
  -- redeemerSameAsDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- redeemerSameAsDatum_0 d1_1 d2_2 _d3_3 = if d1_1 PlutusTx.Eq.== d2_2
  --                                          then GHC.Tuple.Prim.()
  --                                          else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  redeemerSameAsDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x520100002225333573466ebc00c00844800459"
      ]

  -- Preproceesed PlutusV1 Script:
  -- @@@
  -- evenDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                PlutusTx.Builtins.Internal.BuiltinData ->
  --                PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenDatum_0 d1_1 _d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d1_1
  --                                 in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 0
  --                                     then GHC.Tuple.Prim.()
  --                                     else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x581a0100002225333573466e1d20003370c6eb400d20041120011601"
      ]

  -- Preproceesed PlutusV1 Script:
  -- @@@
  -- evenRedeemerNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenRedeemerNoDatum_0 d1_1 _d3_2 = let n_3 = PlutusTx.Builtins.unsafeDataAsI d1_1
  --                                     in if PlutusTx.Prelude.modulo n_3 2 PlutusTx.Eq.== 0
  --                                         then GHC.Tuple.Prim.()
  --                                         else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenRedeemerNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x5819010000225333573466e1d20003370c6eb40092004112001161"
      ]

  -- Preproceesed PlutusV1 Script:
  -- @@@
  -- evenRedeemerWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenRedeemerWithDatum_0 _d1_1 d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d2_2
  --                                             in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 0
  --                                                 then GHC.Tuple.Prim.()
  --                                                 else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenRedeemerWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x581a0100002225333573466e1d20003370c6eb400920041120011601"
      ]

instance PlutusTestScript 'PlutusV2 where
  -- Preproceesed PlutusV2 Script:
  -- @@@
  -- alwaysSucceedsNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysSucceedsNoDatum_0 _ _ = GHC.Tuple.Prim.()
  -- @@@
  alwaysSucceedsNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x4701000022120011"
      ]

  -- Preproceesed PlutusV2 Script:
  -- @@@
  -- alwaysSucceedsWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                              PlutusTx.Builtins.Internal.BuiltinData ->
  --                              PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysSucceedsWithDatum_0 _ _ _ = GHC.Tuple.Prim.()
  -- @@@
  alwaysSucceedsWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x480100002221200101"
      ]

  -- Preproceesed PlutusV2 Script:
  -- @@@
  -- alwaysFailsNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                         PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysFailsNoDatum_0 _ _ = PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  alwaysFailsNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x450100002261"
      ]

  -- Preproceesed PlutusV2 Script:
  -- @@@
  -- alwaysFailsWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                           PlutusTx.Builtins.Internal.BuiltinData ->
  --                           PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysFailsWithDatum_0 _ _ _ = PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  alwaysFailsWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x46010000222601"
      ]

  -- Preproceesed PlutusV2 Script:
  -- @@@
  -- redeemerSameAsDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- redeemerSameAsDatum_0 d1_1 d2_2 _d3_3 = if d1_1 PlutusTx.Eq.== d2_2
  --                                          then GHC.Tuple.Prim.()
  --                                          else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  redeemerSameAsDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x520100002225333573466ebc00c00844800459"
      ]

  -- Preproceesed PlutusV2 Script:
  -- @@@
  -- evenDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                PlutusTx.Builtins.Internal.BuiltinData ->
  --                PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenDatum_0 d1_1 _d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d1_1
  --                                 in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 0
  --                                     then GHC.Tuple.Prim.()
  --                                     else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x581a0100002225333573466e1d20003370c6eb400d20041120011601"
      ]

  -- Preproceesed PlutusV2 Script:
  -- @@@
  -- evenRedeemerNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenRedeemerNoDatum_0 d1_1 _d3_2 = let n_3 = PlutusTx.Builtins.unsafeDataAsI d1_1
  --                                     in if PlutusTx.Prelude.modulo n_3 2 PlutusTx.Eq.== 0
  --                                         then GHC.Tuple.Prim.()
  --                                         else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenRedeemerNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x5819010000225333573466e1d20003370c6eb40092004112001161"
      ]

  -- Preproceesed PlutusV2 Script:
  -- @@@
  -- evenRedeemerWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenRedeemerWithDatum_0 _d1_1 d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d2_2
  --                                             in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 0
  --                                                 then GHC.Tuple.Prim.()
  --                                                 else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenRedeemerWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x581a0100002225333573466e1d20003370c6eb400920041120011601"
      ]

instance PlutusTestScript 'PlutusV3 where
  -- Preproceesed PlutusV3 Script:
  -- @@@
  -- alwaysSucceedsNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysSucceedsNoDatum_0 _ _ = GHC.Tuple.Prim.()
  -- @@@
  alwaysSucceedsNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x46010100228001"
      ]

  -- Preproceesed PlutusV3 Script:
  -- @@@
  -- alwaysSucceedsWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                              PlutusTx.Builtins.Internal.BuiltinData ->
  --                              PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysSucceedsWithDatum_0 _ _ _ = GHC.Tuple.Prim.()
  -- @@@
  alwaysSucceedsWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x4701010022280001"
      ]

  -- Preproceesed PlutusV3 Script:
  -- @@@
  -- alwaysFailsNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                         PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysFailsNoDatum_0 _ _ = PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  alwaysFailsNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x450101002261"
      ]

  -- Preproceesed PlutusV3 Script:
  -- @@@
  -- alwaysFailsWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                           PlutusTx.Builtins.Internal.BuiltinData ->
  --                           PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- alwaysFailsWithDatum_0 _ _ _ = PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  alwaysFailsWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x46010100222601"
      ]

  -- Preproceesed PlutusV3 Script:
  -- @@@
  -- redeemerSameAsDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- redeemerSameAsDatum_0 d1_1 d2_2 _d3_3 = if d1_1 PlutusTx.Eq.== d2_2
  --                                          then GHC.Tuple.Prim.()
  --                                          else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  redeemerSameAsDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x510101002225333573466ebc00c00860002d"
      ]

  -- Preproceesed PlutusV3 Script:
  -- @@@
  -- evenDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                PlutusTx.Builtins.Internal.BuiltinData ->
  --                PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenDatum_0 d1_1 _d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d1_1
  --                                 in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 0
  --                                     then GHC.Tuple.Prim.()
  --                                     else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x58190101002225333573466e1d20003370c6eb400d200418000b01"
      ]

  -- Preproceesed PlutusV3 Script:
  -- @@@
  -- evenRedeemerNoDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                          PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenRedeemerNoDatum_0 d1_1 _d3_2 = let n_3 = PlutusTx.Builtins.unsafeDataAsI d1_1
  --                                     in if PlutusTx.Prelude.modulo n_3 2 PlutusTx.Eq.== 0
  --                                         then GHC.Tuple.Prim.()
  --                                         else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenRedeemerNoDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x5818010100225333573466e1d20003370c6eb4009200418000b1"
      ]

  -- Preproceesed PlutusV3 Script:
  -- @@@
  -- evenRedeemerWithDatum_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData ->
  --                            PlutusTx.Builtins.Internal.BuiltinData -> ()
  -- evenRedeemerWithDatum_0 _d1_1 d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d2_2
  --                                             in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 0
  --                                                 then GHC.Tuple.Prim.()
  --                                                 else PlutusTx.Builtins.error GHC.Tuple.Prim.()
  -- @@@
  evenRedeemerWithDatum _slang =
    decodeHexPlutus . mconcat $
      [ "0x58190101002225333573466e1d20003370c6eb4009200418000b01"
      ]
