id: lazy-environments
language: Haskell
rule:
  kind: strict_field
  inside:
    kind: data_type
    stopBy: end
    has:
      field: name
      regex: '.*Env$'
  has:
    field: type
    pattern: $TYPE
fix: ' $TYPE'
