resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/316c854d1d3089f480708ad5cd5ecf8a74423ddd/snapshot.yaml

packages:
- shelley/chain-and-ledger/executable-spec
- shelley/chain-and-ledger/executable-spec/test
- byron/chain/executable-spec
- byron/ledger/executable-spec
- byron/ledger/impl
- byron/ledger/impl/test
- byron/crypto
- byron/crypto/test
- semantics/executable-spec
- semantics/small-steps-test
- shelley/chain-and-ledger/dependencies/non-integer

ghc-options:
  "$everything": -Wall -fwarn-redundant-constraints

allow-newer: true

extra-deps:
- sequence-0.9.8
- tasty-hedgehog-1.0.0.2 # Needed due to https://github.com/qfpl/tasty-hedgehog/issues/30
- hedgehog-quickcheck-0.1.1
- Unique-0.4.7.6
- bimap-0.4.0
- monad-stm-0.1.0.2
- generic-monoid-0.1.0.0

- git: https://github.com/input-output-hk/cardano-crypto
  commit: 2547ad1e80aeabca2899951601079408becbc92c

- git: https://github.com/input-output-hk/cardano-prelude
  commit: 316c854d1d3089f480708ad5cd5ecf8a74423ddd
  subdirs:
    - .
    - test

- git: https://github.com/input-output-hk/cardano-base
  commit: 7d795c3040ea7785812efa1c97864bbb41b15d3e
  subdirs:
    - binary
    - binary/test
    - cardano-crypto-class
    - slotting

- git: https://github.com/input-output-hk/iohk-monitoring-framework
  commit: efa4b5ecd7f0a13124616b12679cd42517cd905a
  subdirs:
    - contra-tracer

- git: https://github.com/input-output-hk/goblins
  commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
- moo-1.2
- gray-code-0.3.1

nix:
  shell-file: nix/stack-shell.nix
