resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/fa7a16291d3e93b068d9b13620fc81c88b5600f0/snapshot.yaml

packages:
- shelley/chain-and-ledger/executable-spec
- byron/chain/executable-spec
- byron/ledger/executable-spec
- byron/semantics/executable-spec
- shelley/chain-and-ledger/dependencies/non-integer

extra-deps:
- sequence-0.9.8
- tasty-hedgehog-1.0.0.2
- Unique-0.4.7.6
- bimap-0.4.0
- monad-stm-0.1.0.2

- git: https://github.com/input-output-hk/cardano-prelude
  commit: fa7a16291d3e93b068d9b13620fc81c88b5600f0

- git: https://github.com/input-output-hk/cardano-base
  commit: 3c2791584d3f43aa18e9cc13c490239b4c3dcbd2
  subdirs:
    - binary
    - cardano-crypto-class
    - slotting

- git: https://github.com/input-output-hk/goblins
  commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
- moo-1.2
- gray-code-0.3.1

nix:
  shell-file: nix/stack-shell.nix
