resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/57fcc83702b91e0a7aecdb32c99ab1d8c1c444d0/snapshot.yaml

packages:
- shelley/chain-and-ledger/executable-spec
- byron/chain/executable-spec
- byron/ledger/executable-spec
- byron/semantics/executable-spec
- shelley/chain-and-ledger/dependencies/non-integer

ghc-options:
  "$everything": -Wall -fwarn-redundant-constraints

allow-newer: true

extra-deps:
- sequence-0.9.8
- tasty-hedgehog-1.0.0.2 # Needed due to https://github.com/qfpl/tasty-hedgehog/issues/30
- Unique-0.4.7.6
- bimap-0.4.0
- monad-stm-0.1.0.2

- git: https://github.com/input-output-hk/cardano-prelude
  commit: 57fcc83702b91e0a7aecdb32c99ab1d8c1c444d0

- git: https://github.com/input-output-hk/cardano-base
  commit: a7b403c1762a6a122a691df816c26563b7e547f8
  subdirs:
    - binary
    - cardano-crypto-class
    - slotting

- git: https://github.com/input-output-hk/goblins
  commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
- moo-1.2
- gray-code-0.3.1

nix:
  shell-file: nix/stack-shell.nix
