resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3/snapshot.yaml

packages:
  - cardano-ledger
  - cardano-ledger/test
  - crypto
  - crypto/test

extra-deps:
  - tasty-hedgehog-1.0.0.2

  # To be able to use `stack hoogle`
  - haskell-src-exts-1.21.0

  - generic-monoid-0.1.0.0

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 3ac22a2fda11ca7131a011a9ea48fcbfdc26d6b3
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - git: https://github.com/input-output-hk/cardano-base
    commit: 742a789a520387c6cd30a4ca28bc4fc8588a41c7
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: f1d5ddb25531b2512796d34e9cfd803f7af76567
    subdirs:
      - semantics/executable-spec
      - byron/ledger/executable-spec
      - byron/chain/executable-spec

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc
  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 10877fbae54aa7a4c04ae3b5d87c825a4019e9e9
    subdirs:
      - contra-tracer

  # Not yet in Stack
  - bimap-0.4.0

  - Unique-0.4.7.6

nix:
  shell-file: nix/stack-shell.nix
