resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/fda38e60007a019c0c8569e8a0fc08f2102c92cc/snapshot.yaml

packages:
- shelley/chain-and-ledger/executable-spec
- byron/chain/executable-spec
- byron/ledger/executable-spec
- byron/semantics/executable-spec
- shelley/chain-and-ledger/dependencies/non-integer

extra-deps:
- sequence-0.9.8
- tasty-hedgehog-1.0.0.1 # Needed due to https://github.com/qfpl/tasty-hedgehog/issues/30
- Unique-0.4.7.6
- bimap-0.4.0

- git: https://github.com/input-output-hk/cardano-prelude
  commit: fda38e60007a019c0c8569e8a0fc08f2102c92cc

- git: https://github.com/input-output-hk/cardano-base
  commit: 14f9b09920813447a4060b6810bf17fc4ea35840
  subdirs:
    - binary
    - cardano-crypto-class

nix:
  shell-file: nix/stack-shell.nix
