name:                delegation
version:             0.1.0.0
github:              "input-output-hk/shelley-ledger-rules"
author:              "IOHK Formal Metheds Team"
maintainer:          "formal.methods@iohk.io"

description:         Delegation Executable Model

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  dependencies:
  - bytestring
  - containers
  - cryptonite
  - memory
  - multiset
  - tasty
  - tasty-hunit
  - hedgehog
  - tasty-hedgehog
  - tasty-hedgehog-coverage
  - text
  - small-steps

tests:
  delegation-test:
    main:                Tests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-hedgehog
    - tasty-hedgehog-coverage
    - hedgehog
    - delegation
    - cryptonite
    - containers
    - multiset
    - text
