blank_issues_enabled: true
contact_links:
  - name: Contributing guidelines
    url: https://github.com/IntersectMBO/cardano-ledger/blob/master/CONTRIBUTING.md
    about: Some rules & processes we honor.

  - name: All issues
    url: https://github.com/IntersectMBO/cardano-ledger/issues
    about: Check whether your issue is not already covered here.
