name:                accounting
version:             0.1.0.0

description:         accounting

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  dependencies:
  - containers
  - microlens
  - microlens-th

tests:
  accounting-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - accounting
    - containers
    - hedgehog
    - microlens
    - tasty
    - tasty-hedgehog
    - tasty-hunit
