#!/usr/bin/env bash

if [ -z "$GHC_HEAP_LIMIT" ]; then
  exec ghc "$@"
fi

# Set a heap limit in ghc's runtime options
set -- "$@" +RTS "-M${GHC_HEAP_LIMIT}G" -RTS

# Set an OS limit as well, as a backup
ulimit -d $((("$GHC_HEAP_LIMIT" + 2) * 1024 * 1024)) # Allow for 2G additional data use
ulimit -c 0 # Disable core dumping

# Try the build multiple times if it fails with an out-of-memory error
for TRIES_REMAINING in $(seq 4 -1 0); do
  ghc "$@"
  STATUS=$?

  # Status 134 = 128 + 6 is a call to abort() which ghc calls when it can't allocate memory
  if [ "$STATUS" -ne 134 ] || [ "$TRIES_REMAINING" -eq 0 ]; then
    exit "$STATUS"
  fi

  echo "ghc aborted - retrying ($TRIES_REMAINING tries remaining)"
done
