#!/usr/bin/env bash

set -euC

SNAME=cardano-ledger-ghcid

PACKAGES=(
  semantics/executable-spec
  semantics/small-steps-test
  shelley/chain-and-ledger/executable-spec
  shelley/chain-and-ledger/shelley-spec-ledger-test
  shelley-ma/impl
)

ghcid_for_package () {
  local wd="$(pwd)/$1"
  PACKAGE_NAME=$(get_package_name $wd | xargs basename | sed -e "s/.cabal//")
  echo $PACKAGE_NAME
  tmux new-window -d -t "=$SNAME" -n $PACKAGE_NAME -c "$wd"
  tmux send-keys -t "=$SNAME:=$PACKAGE_NAME" 'ghcid' Enter
}

# Get the package name for a given directory
get_package_name () {
  CABAL_FILE=$(find $1 -maxdepth 1 -name "*.cabal")
  echo $CABAL_FILE
}

att() {
    [ -n "${TMUX:-}" ] &&
        tmux switch-client -t "=$SNAME" ||
        tmux attach-session -t "=$SNAME"
}

if tmux has-session -t "=$SNAME" 2> /dev/null; then
    att
    exit 0
fi

tmux new-session -d -s $SNAME
tmux rename-window -t "=$SNAME:0" "cls"

for t in ${PACKAGES[@]}; do
  ghcid_for_package $t
done

att
