#!/usr/bin/env bash

set -euCo pipefail

SNAME=cardano-ledger-ghcid

PACKAGES=(
  libs/small-steps
  eras/shelley/impl
  eras/shelley/test-suite
  eras/shelley-ma/impl
  eras/shelley-ma/shelley-ma-test
)

ghcid_for_package () {
  local WD=$PWD/$1
  PACKAGE_NAME=$(get_package_name "$WD" | xargs basename | sed -e "s/.cabal//")
  echo "$PACKAGE_NAME"
  tmux new-window -d -t "=$SNAME" -n "$PACKAGE_NAME" -c "$WD"
  tmux send-keys -t "=$SNAME:=$PACKAGE_NAME" 'ghcid' Enter
}

# Get the package name for a given directory
get_package_name () {
  find "$1" -maxdepth 1 -name "*.cabal"
}

attach() {
    [ -n "${TMUX:-}" ] &&
        {
          tmux switch-client -t "=$SNAME" ||
          tmux attach-session -t "=$SNAME"
        }
}

if tmux has-session -t "=$SNAME" 2> /dev/null; then
    attach
    exit 0
fi

tmux new-session -d -s $SNAME
tmux rename-window -t "=$SNAME:0" "cls"

for P in "${PACKAGES[@]}"; do
  ghcid_for_package "$P"
done

attach
