-- | This file is generated by plutus-preprocessor/src/Main.hs
module Test.Cardano.Ledger.Alonzo.PlutusScripts where

import Cardano.Ledger.Alonzo.Scripts (Script (..))
import Data.ByteString.Short (pack)

{- Preproceesed Plutus Script
guessTheNumber'2_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
                      PlutusTx.Builtins.Internal.BuiltinData -> ()
guessTheNumber'2_0 d1_1 d2_2 = if d1_1 PlutusTx.Eq.== d2_2
                                then GHC.Tuple.()
                                else PlutusTx.Builtins.error GHC.Tuple.()
-}

guessTheNumber2 :: Script era
guessTheNumber2 =
  (PlutusScript . pack . concat)
    [ [88, 75, 1, 0, 0, 51, 50, 34, 50, 50, 51, 34, 50, 50, 50],
      [0, 18, 35, 51, 83, 0, 147, 51, 80, 7, 0, 128, 2, 0, 18],
      [0, 114, 53, 0, 64, 7, 0, 97, 35, 80, 2, 53, 48, 3, 0],
      [20, 152, 73, 132, 128, 4, 128, 4, 72, 0, 72, 140, 205, 92, 169],
      [155, 174, 0, 32, 1, 0, 80, 4, 18, 32, 2, 18, 32, 1, 32],
      [1, 1]
    ]

{- Preproceesed Plutus Script
guessTheNumber'3_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
                      PlutusTx.Builtins.Internal.BuiltinData ->
                      PlutusTx.Builtins.Internal.BuiltinData -> ()
guessTheNumber'3_0 d1_1 d2_2 _d3_3 = if d1_1 PlutusTx.Eq.== d2_2
                                      then GHC.Tuple.()
                                      else PlutusTx.Builtins.error GHC.Tuple.()
-}

guessTheNumber3 :: Script era
guessTheNumber3 =
  (PlutusScript . pack . concat)
    [ [88, 75, 1, 0, 0, 51, 50, 34, 50, 50, 51, 34, 50, 50, 50],
      [0, 18, 34, 51, 53, 48, 10, 51, 53, 0, 128, 9, 0, 48, 2],
      [32, 8, 35, 80, 5, 0, 128, 7, 18, 53, 0, 35, 83, 0, 48],
      [1, 73, 132, 152, 72, 0, 72, 0, 68, 128, 4, 136, 204, 213, 202],
      [153, 186, 224, 2, 0, 16, 5, 0, 65, 34, 0, 33, 34, 0, 18],
      [0, 17]
    ]

{- Preproceesed Plutus Script
evendata'_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
               PlutusTx.Builtins.Internal.BuiltinData ->
               PlutusTx.Builtins.Internal.BuiltinData -> ()
evendata'_0 d1_1 _d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d1_1
                                in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 0
                                    then GHC.Tuple.()
                                    else PlutusTx.Builtins.error GHC.Tuple.()
-}

evendata3 :: Script era
evendata3 =
  (PlutusScript . pack . concat)
    [ [88, 95, 1, 0, 0, 51, 50, 34, 50, 50, 50, 51, 34, 50, 50],
      [50, 50, 0, 18, 34, 51, 53, 48, 12, 51, 53, 0, 160, 11, 51],
      [0, 83, 0, 64, 3, 72, 1, 18, 0, 2, 0, 146, 53, 0, 112],
      [9, 0, 130, 55, 88, 0, 36, 70, 110, 72, 0, 128, 4, 72, 212],
      [1, 13, 76, 0, 128, 5, 38, 18, 0, 18, 0, 17, 38, 18, 0],
      [18, 35, 51, 87, 42, 102, 226, 64, 8, 0, 64, 20, 1, 4, 136],
      [0, 132, 136, 0, 72, 0, 65]
    ]

{- Preproceesed Plutus Script
odddata'_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
              PlutusTx.Builtins.Internal.BuiltinData ->
              PlutusTx.Builtins.Internal.BuiltinData -> ()
odddata'_0 d1_1 _d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d1_1
                               in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 1
                                   then GHC.Tuple.()
                                   else PlutusTx.Builtins.error GHC.Tuple.()
-}

odddata3 :: Script era
odddata3 =
  (PlutusScript . pack . concat)
    [ [88, 95, 1, 0, 0, 51, 50, 34, 50, 50, 50, 51, 34, 50, 50],
      [50, 50, 0, 18, 34, 51, 53, 48, 12, 51, 53, 0, 160, 11, 51],
      [0, 83, 0, 64, 3, 72, 1, 18, 0, 34, 0, 146, 53, 0, 112],
      [9, 0, 130, 55, 88, 0, 36, 70, 110, 72, 0, 128, 4, 72, 212],
      [1, 13, 76, 0, 128, 5, 38, 18, 0, 18, 0, 17, 38, 18, 0],
      [18, 35, 51, 87, 42, 102, 226, 64, 8, 0, 64, 20, 1, 4, 136],
      [0, 132, 136, 0, 72, 0, 65]
    ]

{- Preproceesed Plutus Script
evenRedeemer'_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
                   PlutusTx.Builtins.Internal.BuiltinData ->
                   PlutusTx.Builtins.Internal.BuiltinData -> ()
evenRedeemer'_0 _d1_1 d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d2_2
                                    in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 0
                                        then GHC.Tuple.()
                                        else PlutusTx.Builtins.error GHC.Tuple.()
-}

evenRedeemer3 :: Script era
evenRedeemer3 =
  (PlutusScript . pack . concat)
    [ [88, 95, 1, 0, 0, 51, 50, 34, 50, 50, 50, 51, 34, 50, 50],
      [50, 50, 0, 18, 34, 51, 53, 48, 12, 51, 53, 0, 160, 11, 51],
      [0, 83, 0, 64, 2, 72, 1, 18, 0, 2, 0, 146, 53, 0, 112],
      [9, 0, 130, 55, 88, 0, 36, 70, 110, 72, 0, 128, 4, 72, 212],
      [1, 13, 76, 0, 128, 5, 38, 18, 0, 18, 0, 17, 38, 18, 0],
      [18, 35, 51, 87, 42, 102, 226, 64, 8, 0, 64, 20, 1, 4, 136],
      [0, 132, 136, 0, 72, 0, 65]
    ]

{- Preproceesed Plutus Script
oddRedeemer'_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
                  PlutusTx.Builtins.Internal.BuiltinData ->
                  PlutusTx.Builtins.Internal.BuiltinData -> ()
oddRedeemer'_0 _d1_1 d2_2 _d3_3 = let n_4 = PlutusTx.Builtins.unsafeDataAsI d2_2
                                   in if PlutusTx.Prelude.modulo n_4 2 PlutusTx.Eq.== 1
                                       then GHC.Tuple.()
                                       else PlutusTx.Builtins.error GHC.Tuple.()
-}

oddRedeemer3 :: Script era
oddRedeemer3 =
  (PlutusScript . pack . concat)
    [ [88, 95, 1, 0, 0, 51, 50, 34, 50, 50, 50, 51, 34, 50, 50],
      [50, 50, 0, 18, 34, 51, 53, 48, 12, 51, 53, 0, 160, 11, 51],
      [0, 83, 0, 64, 2, 72, 1, 18, 0, 34, 0, 146, 53, 0, 112],
      [9, 0, 130, 55, 88, 0, 36, 70, 110, 72, 0, 128, 4, 72, 212],
      [1, 13, 76, 0, 128, 5, 38, 18, 0, 18, 0, 17, 38, 18, 0],
      [18, 35, 51, 87, 42, 102, 226, 64, 8, 0, 64, 20, 1, 4, 136],
      [0, 132, 136, 0, 72, 0, 65]
    ]

{- Preproceesed Plutus Script
sumsTo10'_0 :: PlutusTx.Builtins.Internal.BuiltinData ->
               PlutusTx.Builtins.Internal.BuiltinData ->
               PlutusTx.Builtins.Internal.BuiltinData -> ()
sumsTo10'_0 d1_1 d2_2 _d3_3 = let {m_4 = PlutusTx.Builtins.unsafeDataAsI d1_1;
                                   n_5 = PlutusTx.Builtins.unsafeDataAsI d2_2}
                               in if (m_4 PlutusTx.Numeric.+ n_5) PlutusTx.Eq.== 10
                                   then GHC.Tuple.()
                                   else PlutusTx.Builtins.error GHC.Tuple.()
-}

sumsTo103 :: Script era
sumsTo103 =
  (PlutusScript . pack . concat)
    [ [88, 102, 1, 0, 0, 50, 51, 50, 34, 50, 50, 50, 50, 51, 34],
      [50, 50, 50, 0, 18, 34, 51, 53, 48, 12, 51, 53, 0, 144, 11],
      [51, 53, 0, 160, 15, 48, 4, 0, 51, 0, 64, 2, 72, 5, 8],
      [2, 8, 212, 1, 128, 32, 1, 200, 221, 96, 0, 137, 26, 128, 33],
      [169, 128, 16, 0, 164, 194, 64, 2, 64, 2, 36, 194, 64, 2, 36],
      [0, 36, 70, 102, 174, 84, 205, 196, 128, 16, 0, 128, 40, 2, 9],
      [16, 1, 9, 16, 0, 144, 0, 145, 25, 184, 0, 2, 0, 17]
    ]
